class Signal:
    """
    Representation of a trading signal.
    
    Signals contain information about potential market actions
    and are typically generated by strategies.
    """
    
    def __init__(self, symbol, signal_type, price, 
                 confidence=1.0, rule_id=None, timestamp=None,
                 metadata=None):
        """
        Initialize a signal.
        
        Args:
            symbol: Instrument symbol
            signal_type: Signal type (BUY, SELL, NEUTRAL)
            price: Price at signal generation
            confidence: Signal confidence (0-1)
            rule_id: Optional ID of the rule that generated the signal
            timestamp: Signal timestamp (defaults to current time)
            metadata: Optional additional signal metadata
        """
        self.symbol = symbol
        self.signal_type = signal_type
        self.price = price
        self.confidence = confidence
        self.rule_id = rule_id
        self.timestamp = timestamp or datetime.datetime.now()
        self.metadata = metadata or {}
    
    def __str__(self):
        return f"Signal({self.symbol}, {self.signal_type}, price={self.price}, confidence={self.confidence})"
